from boolean_fucntion import boolean_function
print("*******************************")
print("Simulador de funções booleanas")
print("*******************************")

print("Digite sua função booleana abaixo:")
print("OBS: para AND -> *, para OR -> + e para NOT -> '")
function = input()
vars = boolean_function.variables(function)
print(vars)
vars_values = boolean_function.get_value_variables(vars)
print(vars_values)
new_function = boolean_function.build_function(function, vars_values)
print(f"A função booleana {function} é: {new_function}")
result = boolean_function.eval_function(new_function)
print(f"O resultado da função booleana {function} é: {result}")
